### PR TITLE
RDM-9354 Case Sensitive CaseRole on Add Case-Assigned Users and Roles endpoint

### PR DESCRIPTION
**Pull request by smathangi**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDM-9354

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by rajaram-nagarajan — APPROVED** [review]
LGTM

**Review by MSancaktutar — APPROVED** [review]
Looks good, but could we also double check there is no duplicated persistence logic for this to applied to further, around the case_users table?

**Comment by smathangi** [comment]
> Looks good, but could we also double check there is no duplicated persistence logic for this to applied to further, around the case_users table?

at the moment grant api is passing role implicitly (CREATOR).. so no issues there. We could even push this check into repository level so that we can guard for all future usages. But repository should throw a validation error rather than suppressing silently. (callers can suppress if they wish to..). Please let me know your thoughts @MSancaktutar

**Comment by MSancaktutar** [comment]
> > Looks good, but could we also double check there is no duplicated persistence logic for this to applied to further, around the case_users table?
> 
> at the moment grant api is passing role implicitly (CREATOR).. so no issues there. We could even push this check into repository level so that we can guard for all future usages. But repository should throw a validation error rather than suppressing silently. (callers can suppress if they wish to..). Please let me know your thoughts @MSancaktutar

Such a change will go too much beyond the purpose of this change. So, this improvement should now be sufficient.

**Pull request merged**
