### PR TITLE
RDM-12121: Code cleanup for Fortify issues

### PR DESCRIPTION
**Pull request by smathangi**
### JIRA link ###

https://tools.hmcts.net/jira/browse/RDM-12121

### Change description ###

Code has been cleaned up as part of Fortify issues reported on RDM-12079, 12087, 12095

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by MSancaktutar — APPROVED** [review]
LGTM

**Comment by MSancaktutar** [comment]
@rajaram-nagarajan  - Could you please resolve conflicts?

**Comment by rajaram-nagarajan** [comment]
> @rajaram-nagarajan - Could you please resolve conflicts?

Resolved

**Review by MSancaktutar — APPROVED** [review]
LGTM

**Pull request merged**
