### PR TITLE
added new S2S service wa_task_configuration_api

### PR DESCRIPTION
**Pull request by smathangi**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by tomxelliott — APPROVED** [review]

**Review by alexbaeza — APPROVED** [review]

**Comment by hemantt** [comment]
LGTM, Happy for this to go CICD

**Review by MSancaktutar — CHANGES_REQUESTED** [review]
This could be better done with a flux change on lower envs first and then on prod with another flux change, couldn't it?

**Review by MSancaktutar — CHANGES_REQUESTED** [review]
Flux config will overwrite this.
This needs to be updated on flux.

**Comment by MSancaktutar** [comment]
I understand this is now being managed with flux, hence closing the PR.

**Pull request closed without merging**
